FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY index.html ./
COPY tsconfig.json ./
COPY vite.config.js ./
COPY src ./src

ARG VITE_API_BASE_URL
ARG VITE_CRM_API_URL
ARG VITE_ADMIN_LOGIN
ARG VITE_ADMIN_PASS
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_CRM_API_URL=$VITE_CRM_API_URL
ENV VITE_ADMIN_LOGIN=$VITE_ADMIN_LOGIN
ENV VITE_ADMIN_PASS=$VITE_ADMIN_PASS

RUN npm run build

FROM nginx:1.27-alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

