export const TICKET_STATUS = [
  "ABERTO",
  "EM_ATENDIMENTO",
  "AGUARDANDO_CLIENTE",
  "AGUARDANDO_ESTOQUE",
  "FECHADO"
] as const;

export const PIPELINE_STAGES = [
  "NOVO LEAD",
  "ORCAMENTO EM MONTAGEM",
  "ORCAMENTO ENVIADO",
  "NEGOCIACAO",
  "FECHADO - GANHO",
  "FECHADO - PERDIDO"
] as const;
